# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 04:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dranimate_restful.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puppet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('mesh', models.FileField(upload_to=dranimate_restful.models.Puppet.update_meshname, verbose_name='mesh data (encoded in ply)')),
                ('rig', models.FileField(upload_to='meshes/', verbose_name='rig data (encoded in xml)')),
                ('image', models.ImageField(upload_to='imgs/', verbose_name='image data (encoded in jpg)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('puppet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dranimate_restful.Puppet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecordSceneAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puppet_x_position', models.DecimalField(decimal_places=10, max_digits=19)),
                ('puppet_y_position', models.DecimalField(decimal_places=10, max_digits=19)),
                ('puppet_x_scale', models.DecimalField(decimal_places=10, max_digits=19)),
                ('puppet_y_scale', models.DecimalField(decimal_places=10, max_digits=19)),
                ('puppet_rotate', models.DecimalField(decimal_places=10, max_digits=19)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dranimate_restful.Recording')),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='upload date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recordsceneassociation',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dranimate_restful.Scene'),
        ),
        migrations.AddField(
            model_name='recordsceneassociation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
